/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.26 at 06:59:21 PM BST 
//


package org.omg.dmn.tck.marshaller._20160719;

import java.util.ArrayList;
import java.util.Collection;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="modelName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="labels" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="label" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="testCase" maxOccurs="unbounded"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="inputNode" maxOccurs="unbounded"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;extension base="{http://www.omg.org/spec/DMN/20160719/testcase}valueType"&gt;
 *                           &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *                           &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                         &lt;/extension&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="resultNode" maxOccurs="unbounded" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="computed" type="{http://www.omg.org/spec/DMN/20160719/testcase}valueType" minOccurs="0"/&gt;
 *                             &lt;element name="expected" type="{http://www.omg.org/spec/DMN/20160719/testcase}valueType" minOccurs="0"/&gt;
 *                           &lt;/sequence&gt;
 *                           &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *                           &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "modelName",
    "labels",
    "testCase"
})
@XmlRootElement(name = "testCases")
public class TestCases {

    protected String modelName;
    protected TestCases.Labels labels;
    @XmlElement(required = true)
    protected java.util.List<TestCases.TestCase> testCase;

    /**
     * Gets the value of the modelName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModelName() {
        return modelName;
    }

    /**
     * Sets the value of the modelName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModelName(String value) {
        this.modelName = value;
    }

    /**
     * Gets the value of the labels property.
     * 
     * @return
     *     possible object is
     *     {@link TestCases.Labels }
     *     
     */
    public TestCases.Labels getLabels() {
        return labels;
    }

    /**
     * Sets the value of the labels property.
     * 
     * @param value
     *     allowed object is
     *     {@link TestCases.Labels }
     *     
     */
    public void setLabels(TestCases.Labels value) {
        this.labels = value;
    }

    /**
     * Gets the value of the testCase property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the testCase property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTestCase().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TestCases.TestCase }
     * 
     * 
     */
    public java.util.List<TestCases.TestCase> getTestCase() {
        if (testCase == null) {
            testCase = new ArrayList<TestCases.TestCase>();
        }
        return this.testCase;
    }

    public TestCases withModelName(String value) {
        setModelName(value);
        return this;
    }

    public TestCases withLabels(TestCases.Labels value) {
        setLabels(value);
        return this;
    }

    public TestCases withTestCase(TestCases.TestCase... values) {
        if (values!= null) {
            for (TestCases.TestCase value: values) {
                getTestCase().add(value);
            }
        }
        return this;
    }

    public TestCases withTestCase(Collection<TestCases.TestCase> values) {
        if (values!= null) {
            getTestCase().addAll(values);
        }
        return this;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="label" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "label"
    })
    public static class Labels {

        protected java.util.List<String> label;

        /**
         * Gets the value of the label property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the label property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getLabel().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public java.util.List<String> getLabel() {
            if (label == null) {
                label = new ArrayList<String>();
            }
            return this.label;
        }

        public TestCases.Labels withLabel(String... values) {
            if (values!= null) {
                for (String value: values) {
                    getLabel().add(value);
                }
            }
            return this;
        }

        public TestCases.Labels withLabel(Collection<String> values) {
            if (values!= null) {
                getLabel().addAll(values);
            }
            return this;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="inputNode" maxOccurs="unbounded"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;extension base="{http://www.omg.org/spec/DMN/20160719/testcase}valueType"&gt;
     *                 &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
     *                 &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *               &lt;/extension&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="resultNode" maxOccurs="unbounded" minOccurs="0"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="computed" type="{http://www.omg.org/spec/DMN/20160719/testcase}valueType" minOccurs="0"/&gt;
     *                   &lt;element name="expected" type="{http://www.omg.org/spec/DMN/20160719/testcase}valueType" minOccurs="0"/&gt;
     *                 &lt;/sequence&gt;
     *                 &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
     *                 &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "description",
        "inputNode",
        "resultNode"
    })
    public static class TestCase {

        protected String description;
        @XmlElement(required = true)
        protected java.util.List<TestCases.TestCase.InputNode> inputNode;
        protected java.util.List<TestCases.TestCase.ResultNode> resultNode;
        @XmlAttribute(name = "id")
        protected String id;

        /**
         * Gets the value of the description property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDescription() {
            return description;
        }

        /**
         * Sets the value of the description property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDescription(String value) {
            this.description = value;
        }

        /**
         * Gets the value of the inputNode property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the inputNode property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getInputNode().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TestCases.TestCase.InputNode }
         * 
         * 
         */
        public java.util.List<TestCases.TestCase.InputNode> getInputNode() {
            if (inputNode == null) {
                inputNode = new ArrayList<TestCases.TestCase.InputNode>();
            }
            return this.inputNode;
        }

        /**
         * Gets the value of the resultNode property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the resultNode property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getResultNode().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TestCases.TestCase.ResultNode }
         * 
         * 
         */
        public java.util.List<TestCases.TestCase.ResultNode> getResultNode() {
            if (resultNode == null) {
                resultNode = new ArrayList<TestCases.TestCase.ResultNode>();
            }
            return this.resultNode;
        }

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setId(String value) {
            this.id = value;
        }

        public TestCases.TestCase withDescription(String value) {
            setDescription(value);
            return this;
        }

        public TestCases.TestCase withInputNode(TestCases.TestCase.InputNode... values) {
            if (values!= null) {
                for (TestCases.TestCase.InputNode value: values) {
                    getInputNode().add(value);
                }
            }
            return this;
        }

        public TestCases.TestCase withInputNode(Collection<TestCases.TestCase.InputNode> values) {
            if (values!= null) {
                getInputNode().addAll(values);
            }
            return this;
        }

        public TestCases.TestCase withResultNode(TestCases.TestCase.ResultNode... values) {
            if (values!= null) {
                for (TestCases.TestCase.ResultNode value: values) {
                    getResultNode().add(value);
                }
            }
            return this;
        }

        public TestCases.TestCase withResultNode(Collection<TestCases.TestCase.ResultNode> values) {
            if (values!= null) {
                getResultNode().addAll(values);
            }
            return this;
        }

        public TestCases.TestCase withId(String value) {
            setId(value);
            return this;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;extension base="{http://www.omg.org/spec/DMN/20160719/testcase}valueType"&gt;
         *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
         *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *     &lt;/extension&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class InputNode
            extends ValueType
        {

            @XmlAttribute(name = "name", required = true)
            @XmlSchemaType(name = "anySimpleType")
            protected String name;
            @XmlAttribute(name = "type")
            protected String type;

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the type property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getType() {
                return type;
            }

            /**
             * Sets the value of the type property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setType(String value) {
                this.type = value;
            }

            public TestCases.TestCase.InputNode withName(String value) {
                setName(value);
                return this;
            }

            public TestCases.TestCase.InputNode withType(String value) {
                setType(value);
                return this;
            }

            @Override
            public TestCases.TestCase.InputNode withValue(Object value) {
                setValue(value);
                return this;
            }

            @Override
            public TestCases.TestCase.InputNode withComponent(ValueType.Component... values) {
                if (values!= null) {
                    for (ValueType.Component value: values) {
                        getComponent().add(value);
                    }
                }
                return this;
            }

            @Override
            public TestCases.TestCase.InputNode withComponent(Collection<ValueType.Component> values) {
                if (values!= null) {
                    getComponent().addAll(values);
                }
                return this;
            }

            @Override
            public TestCases.TestCase.InputNode withList(ValueType.List value) {
                setList(value);
                return this;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="computed" type="{http://www.omg.org/spec/DMN/20160719/testcase}valueType" minOccurs="0"/&gt;
         *         &lt;element name="expected" type="{http://www.omg.org/spec/DMN/20160719/testcase}valueType" minOccurs="0"/&gt;
         *       &lt;/sequence&gt;
         *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
         *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "computed",
            "expected"
        })
        public static class ResultNode {

            protected ValueType computed;
            protected ValueType expected;
            @XmlAttribute(name = "name", required = true)
            @XmlSchemaType(name = "anySimpleType")
            protected String name;
            @XmlAttribute(name = "type")
            protected String type;

            /**
             * Gets the value of the computed property.
             * 
             * @return
             *     possible object is
             *     {@link ValueType }
             *     
             */
            public ValueType getComputed() {
                return computed;
            }

            /**
             * Sets the value of the computed property.
             * 
             * @param value
             *     allowed object is
             *     {@link ValueType }
             *     
             */
            public void setComputed(ValueType value) {
                this.computed = value;
            }

            /**
             * Gets the value of the expected property.
             * 
             * @return
             *     possible object is
             *     {@link ValueType }
             *     
             */
            public ValueType getExpected() {
                return expected;
            }

            /**
             * Sets the value of the expected property.
             * 
             * @param value
             *     allowed object is
             *     {@link ValueType }
             *     
             */
            public void setExpected(ValueType value) {
                this.expected = value;
            }

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the type property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getType() {
                return type;
            }

            /**
             * Sets the value of the type property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setType(String value) {
                this.type = value;
            }

            public TestCases.TestCase.ResultNode withComputed(ValueType value) {
                setComputed(value);
                return this;
            }

            public TestCases.TestCase.ResultNode withExpected(ValueType value) {
                setExpected(value);
                return this;
            }

            public TestCases.TestCase.ResultNode withName(String value) {
                setName(value);
                return this;
            }

            public TestCases.TestCase.ResultNode withType(String value) {
                setType(value);
                return this;
            }

        }

    }

}
