vendor.name=OpenWerk
vendor.url=https://github.com/openwerk
product.name=openwerk/dmn
product.url=https://github.com/OpenWerk/dmn
product.version=1.0.0
product.comment=Pure PHP framework-agnostic DMN decision engine.
instructions.url=https://github.com/OpenWerk/dmn#conformance-check-it-yourself
last.update=2026-07-21
